### ISSUE TITLE
Some :not pseudo selectors are too specific for the high level design they are meant to acheive

### ISSUE THREAD

**Issue by robertsoniv** [ionlyseespots/ambient-design#66]
For example: 

``` css
nav[am-layout] a:not(.am-floating-action) {
    display: inline-block;
    font-size: 14px;
    font-weight: 400;
    line-height: 36px;
    padding: 1em;
    text-decoration: none;
}
```

This rule will prevent me from overriding some commonly changed styles on the <a> tags by using a custom design pattern attribute on `nav[am-layout]` (which is how I would like to alter things like this)
