### ISSUE TITLE
Article should not wrap on portrait

### ISSUE THREAD

**Issue by robertsoniv** [ionlyseespots/ambient-design#68]
Because the only rule that changes for `<article>` elements on the portrait orientation is 

``` css
article {
     flex-direction:column;
}
```

The sections inside will wrap side by side if there is not enough vertical space.
The rule here should be...

``` css
article {
     flex-flow:column nowrap;
}
```
